#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtdatavis3d
Version  : 5.12.4
Release  : 11
URL      : https://download.qt.io/official_releases/qt/5.12/5.12.4/submodules/qtdatavis3d-everywhere-src-5.12.4.tar.xz
Source0  : https://download.qt.io/official_releases/qt/5.12/5.12.4/submodules/qtdatavis3d-everywhere-src-5.12.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: qtdatavis3d-lib = %{version}-%{release}
Requires: qtdatavis3d-license = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Multimedia)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5Widgets)

%description
---------------------------
Qt Data Visualization 5.9.0
---------------------------

%package dev
Summary: dev components for the qtdatavis3d package.
Group: Development
Requires: qtdatavis3d-lib = %{version}-%{release}
Provides: qtdatavis3d-devel = %{version}-%{release}
Requires: qtdatavis3d = %{version}-%{release}

%description dev
dev components for the qtdatavis3d package.


%package lib
Summary: lib components for the qtdatavis3d package.
Group: Libraries
Requires: qtdatavis3d-license = %{version}-%{release}

%description lib
lib components for the qtdatavis3d package.


%package license
Summary: license components for the qtdatavis3d package.
Group: Default

%description license
license components for the qtdatavis3d package.


%prep
%setup -q -n qtdatavis3d-everywhere-src-5.12.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1561177615
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtdatavis3d
cp LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/qtdatavis3d/LICENSE.GPL3
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/abstract3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/abstract3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/abstractitemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/abstractobjecthelper_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/abstractrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/axisrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/baritemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/barrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/bars3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/bars3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/barseriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/camerahelper_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/customrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/datavisualizationglobal_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/drawer_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/labelitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/meshloader_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/objecthelper_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dbars_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dcamera_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dinputhandler_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dlight_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dobject_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dscatter_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dscene_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dsurface_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/q3dtheme_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qabstract3daxis_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qabstract3dgraph_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qabstract3dinputhandler_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qabstract3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qabstractdataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qbar3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qbardataitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qbardataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qcategory3daxis_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qcustom3ditem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qcustom3dlabel_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qcustom3dvolume_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qheightmapsurfacedataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qitemmodelbardataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qitemmodelscatterdataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qitemmodelsurfacedataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qlogvalue3daxisformatter_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qscatter3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qscatterdataitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qscatterdataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qsurface3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qsurfacedataitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qsurfacedataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qtouch3dinputhandler_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qvalue3daxis_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/qvalue3daxisformatter_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/scatter3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/scatter3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/scatteritemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/scatterobjectbufferhelper_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/scatterpointbufferhelper_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/scatterrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/scatterseriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/selectionpointer_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/seriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/shaderhelper_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/surface3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/surface3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/surfaceitemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/surfaceobject_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/surfaceseriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/texturehelper_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/thememanager_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/utils_p.h
/usr/include/qt5/QtDataVisualization/5.12.4/QtDataVisualization/private/vertexindexer_p.h
/usr/include/qt5/QtDataVisualization/Q3DBars
/usr/include/qt5/QtDataVisualization/Q3DCamera
/usr/include/qt5/QtDataVisualization/Q3DInputHandler
/usr/include/qt5/QtDataVisualization/Q3DLight
/usr/include/qt5/QtDataVisualization/Q3DObject
/usr/include/qt5/QtDataVisualization/Q3DScatter
/usr/include/qt5/QtDataVisualization/Q3DScene
/usr/include/qt5/QtDataVisualization/Q3DSurface
/usr/include/qt5/QtDataVisualization/Q3DTheme
/usr/include/qt5/QtDataVisualization/QAbstract3DAxis
/usr/include/qt5/QtDataVisualization/QAbstract3DGraph
/usr/include/qt5/QtDataVisualization/QAbstract3DInputHandler
/usr/include/qt5/QtDataVisualization/QAbstract3DSeries
/usr/include/qt5/QtDataVisualization/QAbstractDataProxy
/usr/include/qt5/QtDataVisualization/QBar3DSeries
/usr/include/qt5/QtDataVisualization/QBarDataArray
/usr/include/qt5/QtDataVisualization/QBarDataItem
/usr/include/qt5/QtDataVisualization/QBarDataProxy
/usr/include/qt5/QtDataVisualization/QBarDataRow
/usr/include/qt5/QtDataVisualization/QCategory3DAxis
/usr/include/qt5/QtDataVisualization/QCustom3DItem
/usr/include/qt5/QtDataVisualization/QCustom3DLabel
/usr/include/qt5/QtDataVisualization/QCustom3DVolume
/usr/include/qt5/QtDataVisualization/QHeightMapSurfaceDataProxy
/usr/include/qt5/QtDataVisualization/QItemModelBarDataProxy
/usr/include/qt5/QtDataVisualization/QItemModelScatterDataProxy
/usr/include/qt5/QtDataVisualization/QItemModelSurfaceDataProxy
/usr/include/qt5/QtDataVisualization/QLogValue3DAxisFormatter
/usr/include/qt5/QtDataVisualization/QScatter3DSeries
/usr/include/qt5/QtDataVisualization/QScatterDataArray
/usr/include/qt5/QtDataVisualization/QScatterDataItem
/usr/include/qt5/QtDataVisualization/QScatterDataProxy
/usr/include/qt5/QtDataVisualization/QSurface3DSeries
/usr/include/qt5/QtDataVisualization/QSurfaceDataArray
/usr/include/qt5/QtDataVisualization/QSurfaceDataItem
/usr/include/qt5/QtDataVisualization/QSurfaceDataProxy
/usr/include/qt5/QtDataVisualization/QSurfaceDataRow
/usr/include/qt5/QtDataVisualization/QTouch3DInputHandler
/usr/include/qt5/QtDataVisualization/QValue3DAxis
/usr/include/qt5/QtDataVisualization/QValue3DAxisFormatter
/usr/include/qt5/QtDataVisualization/QtDataVisualization
/usr/include/qt5/QtDataVisualization/QtDataVisualizationDepends
/usr/include/qt5/QtDataVisualization/QtDataVisualizationVersion
/usr/include/qt5/QtDataVisualization/q3dbars.h
/usr/include/qt5/QtDataVisualization/q3dcamera.h
/usr/include/qt5/QtDataVisualization/q3dinputhandler.h
/usr/include/qt5/QtDataVisualization/q3dlight.h
/usr/include/qt5/QtDataVisualization/q3dobject.h
/usr/include/qt5/QtDataVisualization/q3dscatter.h
/usr/include/qt5/QtDataVisualization/q3dscene.h
/usr/include/qt5/QtDataVisualization/q3dsurface.h
/usr/include/qt5/QtDataVisualization/q3dtheme.h
/usr/include/qt5/QtDataVisualization/qabstract3daxis.h
/usr/include/qt5/QtDataVisualization/qabstract3dgraph.h
/usr/include/qt5/QtDataVisualization/qabstract3dinputhandler.h
/usr/include/qt5/QtDataVisualization/qabstract3dseries.h
/usr/include/qt5/QtDataVisualization/qabstractdataproxy.h
/usr/include/qt5/QtDataVisualization/qbar3dseries.h
/usr/include/qt5/QtDataVisualization/qbardataitem.h
/usr/include/qt5/QtDataVisualization/qbardataproxy.h
/usr/include/qt5/QtDataVisualization/qcategory3daxis.h
/usr/include/qt5/QtDataVisualization/qcustom3ditem.h
/usr/include/qt5/QtDataVisualization/qcustom3dlabel.h
/usr/include/qt5/QtDataVisualization/qcustom3dvolume.h
/usr/include/qt5/QtDataVisualization/qdatavisualizationglobal.h
/usr/include/qt5/QtDataVisualization/qheightmapsurfacedataproxy.h
/usr/include/qt5/QtDataVisualization/qitemmodelbardataproxy.h
/usr/include/qt5/QtDataVisualization/qitemmodelscatterdataproxy.h
/usr/include/qt5/QtDataVisualization/qitemmodelsurfacedataproxy.h
/usr/include/qt5/QtDataVisualization/qlogvalue3daxisformatter.h
/usr/include/qt5/QtDataVisualization/qscatter3dseries.h
/usr/include/qt5/QtDataVisualization/qscatterdataitem.h
/usr/include/qt5/QtDataVisualization/qscatterdataproxy.h
/usr/include/qt5/QtDataVisualization/qsurface3dseries.h
/usr/include/qt5/QtDataVisualization/qsurfacedataitem.h
/usr/include/qt5/QtDataVisualization/qsurfacedataproxy.h
/usr/include/qt5/QtDataVisualization/qtdatavisualizationversion.h
/usr/include/qt5/QtDataVisualization/qtouch3dinputhandler.h
/usr/include/qt5/QtDataVisualization/qutils.h
/usr/include/qt5/QtDataVisualization/qvalue3daxis.h
/usr/include/qt5/QtDataVisualization/qvalue3daxisformatter.h
/usr/lib64/cmake/Qt5DataVisualization/Qt5DataVisualizationConfig.cmake
/usr/lib64/cmake/Qt5DataVisualization/Qt5DataVisualizationConfigVersion.cmake
/usr/lib64/libQt5DataVisualization.prl
/usr/lib64/libQt5DataVisualization.so
/usr/lib64/pkgconfig/Qt5DataVisualization.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5DataVisualization.so.5
/usr/lib64/libQt5DataVisualization.so.5.12
/usr/lib64/libQt5DataVisualization.so.5.12.4
/usr/lib64/qt5/qml/QtDataVisualization/designer/Bars3DSpecifics.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/Scatter3DSpecifics.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/Surface3DSpecifics.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/default/Bars3D.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/default/Scatter3D.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/default/Surface3D.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/bars3d-icon.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/bars3d-icon16.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/scatter3d-icon.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/scatter3d-icon16.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/surface3d-icon.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/surface3d-icon16.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/qtdatavisualization.metainfo
/usr/lib64/qt5/qml/QtDataVisualization/libdatavisualizationqml2.so
/usr/lib64/qt5/qml/QtDataVisualization/plugins.qmltypes
/usr/lib64/qt5/qml/QtDataVisualization/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtdatavis3d/LICENSE.GPL3
