#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtdatavis3d
Version  : 5.15.2
Release  : 22
URL      : https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtdatavis3d-everywhere-src-5.15.2.tar.xz
Source0  : https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtdatavis3d-everywhere-src-5.15.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: qtdatavis3d-lib = %{version}-%{release}
Requires: qtdatavis3d-license = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Multimedia)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5Widgets)
Patch1: qtdatavis3d-stable-branch.patch

%description
---------------------------
Qt Data Visualization 5.9.0
---------------------------

%package dev
Summary: dev components for the qtdatavis3d package.
Group: Development
Requires: qtdatavis3d-lib = %{version}-%{release}
Provides: qtdatavis3d-devel = %{version}-%{release}
Requires: qtdatavis3d = %{version}-%{release}

%description dev
dev components for the qtdatavis3d package.


%package examples
Summary: examples components for the qtdatavis3d package.
Group: Default
Requires: qtdatavis3d-dev = %{version}-%{release}

%description examples
examples components for the qtdatavis3d package.


%package lib
Summary: lib components for the qtdatavis3d package.
Group: Libraries
Requires: qtdatavis3d-license = %{version}-%{release}

%description lib
lib components for the qtdatavis3d package.


%package license
Summary: license components for the qtdatavis3d package.
Group: Default

%description license
license components for the qtdatavis3d package.


%prep
%setup -q -n qtdatavis3d-everywhere-src-5.15.2
cd %{_builddir}/qtdatavis3d-everywhere-src-5.15.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1662655443
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtdatavis3d
cp %{_builddir}/qtdatavis3d-everywhere-src-%{version}/LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/qtdatavis3d/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/abstract3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/abstract3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/abstractitemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/abstractobjecthelper_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/abstractrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/axisrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/baritemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/barrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/bars3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/bars3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/barseriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/camerahelper_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/customrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/datavisualizationglobal_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/drawer_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/labelitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/meshloader_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/objecthelper_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dbars_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dcamera_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dinputhandler_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dlight_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dobject_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dscatter_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dscene_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dsurface_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/q3dtheme_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qabstract3daxis_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qabstract3dgraph_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qabstract3dinputhandler_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qabstract3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qabstractdataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qbar3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qbardataitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qbardataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qcategory3daxis_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qcustom3ditem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qcustom3dlabel_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qcustom3dvolume_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qheightmapsurfacedataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qitemmodelbardataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qitemmodelscatterdataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qitemmodelsurfacedataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qlogvalue3daxisformatter_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qscatter3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qscatterdataitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qscatterdataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qsurface3dseries_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qsurfacedataitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qsurfacedataproxy_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qtouch3dinputhandler_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qvalue3daxis_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/qvalue3daxisformatter_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/scatter3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/scatter3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/scatteritemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/scatterobjectbufferhelper_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/scatterpointbufferhelper_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/scatterrenderitem_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/scatterseriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/selectionpointer_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/seriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/shaderhelper_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/surface3dcontroller_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/surface3drenderer_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/surfaceitemmodelhandler_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/surfaceobject_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/surfaceseriesrendercache_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/texturehelper_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/thememanager_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/utils_p.h
/usr/include/qt5/QtDataVisualization/5.15.2/QtDataVisualization/private/vertexindexer_p.h
/usr/include/qt5/QtDataVisualization/Q3DBars
/usr/include/qt5/QtDataVisualization/Q3DCamera
/usr/include/qt5/QtDataVisualization/Q3DInputHandler
/usr/include/qt5/QtDataVisualization/Q3DLight
/usr/include/qt5/QtDataVisualization/Q3DObject
/usr/include/qt5/QtDataVisualization/Q3DScatter
/usr/include/qt5/QtDataVisualization/Q3DScene
/usr/include/qt5/QtDataVisualization/Q3DSurface
/usr/include/qt5/QtDataVisualization/Q3DTheme
/usr/include/qt5/QtDataVisualization/QAbstract3DAxis
/usr/include/qt5/QtDataVisualization/QAbstract3DGraph
/usr/include/qt5/QtDataVisualization/QAbstract3DInputHandler
/usr/include/qt5/QtDataVisualization/QAbstract3DSeries
/usr/include/qt5/QtDataVisualization/QAbstractDataProxy
/usr/include/qt5/QtDataVisualization/QBar3DSeries
/usr/include/qt5/QtDataVisualization/QBarDataArray
/usr/include/qt5/QtDataVisualization/QBarDataItem
/usr/include/qt5/QtDataVisualization/QBarDataProxy
/usr/include/qt5/QtDataVisualization/QBarDataRow
/usr/include/qt5/QtDataVisualization/QCategory3DAxis
/usr/include/qt5/QtDataVisualization/QCustom3DItem
/usr/include/qt5/QtDataVisualization/QCustom3DLabel
/usr/include/qt5/QtDataVisualization/QCustom3DVolume
/usr/include/qt5/QtDataVisualization/QHeightMapSurfaceDataProxy
/usr/include/qt5/QtDataVisualization/QItemModelBarDataProxy
/usr/include/qt5/QtDataVisualization/QItemModelScatterDataProxy
/usr/include/qt5/QtDataVisualization/QItemModelSurfaceDataProxy
/usr/include/qt5/QtDataVisualization/QLogValue3DAxisFormatter
/usr/include/qt5/QtDataVisualization/QScatter3DSeries
/usr/include/qt5/QtDataVisualization/QScatterDataArray
/usr/include/qt5/QtDataVisualization/QScatterDataItem
/usr/include/qt5/QtDataVisualization/QScatterDataProxy
/usr/include/qt5/QtDataVisualization/QSurface3DSeries
/usr/include/qt5/QtDataVisualization/QSurfaceDataArray
/usr/include/qt5/QtDataVisualization/QSurfaceDataItem
/usr/include/qt5/QtDataVisualization/QSurfaceDataProxy
/usr/include/qt5/QtDataVisualization/QSurfaceDataRow
/usr/include/qt5/QtDataVisualization/QTouch3DInputHandler
/usr/include/qt5/QtDataVisualization/QValue3DAxis
/usr/include/qt5/QtDataVisualization/QValue3DAxisFormatter
/usr/include/qt5/QtDataVisualization/QtDataVisualization
/usr/include/qt5/QtDataVisualization/QtDataVisualizationDepends
/usr/include/qt5/QtDataVisualization/QtDataVisualizationVersion
/usr/include/qt5/QtDataVisualization/q3dbars.h
/usr/include/qt5/QtDataVisualization/q3dcamera.h
/usr/include/qt5/QtDataVisualization/q3dinputhandler.h
/usr/include/qt5/QtDataVisualization/q3dlight.h
/usr/include/qt5/QtDataVisualization/q3dobject.h
/usr/include/qt5/QtDataVisualization/q3dscatter.h
/usr/include/qt5/QtDataVisualization/q3dscene.h
/usr/include/qt5/QtDataVisualization/q3dsurface.h
/usr/include/qt5/QtDataVisualization/q3dtheme.h
/usr/include/qt5/QtDataVisualization/qabstract3daxis.h
/usr/include/qt5/QtDataVisualization/qabstract3dgraph.h
/usr/include/qt5/QtDataVisualization/qabstract3dinputhandler.h
/usr/include/qt5/QtDataVisualization/qabstract3dseries.h
/usr/include/qt5/QtDataVisualization/qabstractdataproxy.h
/usr/include/qt5/QtDataVisualization/qbar3dseries.h
/usr/include/qt5/QtDataVisualization/qbardataitem.h
/usr/include/qt5/QtDataVisualization/qbardataproxy.h
/usr/include/qt5/QtDataVisualization/qcategory3daxis.h
/usr/include/qt5/QtDataVisualization/qcustom3ditem.h
/usr/include/qt5/QtDataVisualization/qcustom3dlabel.h
/usr/include/qt5/QtDataVisualization/qcustom3dvolume.h
/usr/include/qt5/QtDataVisualization/qdatavisualizationglobal.h
/usr/include/qt5/QtDataVisualization/qheightmapsurfacedataproxy.h
/usr/include/qt5/QtDataVisualization/qitemmodelbardataproxy.h
/usr/include/qt5/QtDataVisualization/qitemmodelscatterdataproxy.h
/usr/include/qt5/QtDataVisualization/qitemmodelsurfacedataproxy.h
/usr/include/qt5/QtDataVisualization/qlogvalue3daxisformatter.h
/usr/include/qt5/QtDataVisualization/qscatter3dseries.h
/usr/include/qt5/QtDataVisualization/qscatterdataitem.h
/usr/include/qt5/QtDataVisualization/qscatterdataproxy.h
/usr/include/qt5/QtDataVisualization/qsurface3dseries.h
/usr/include/qt5/QtDataVisualization/qsurfacedataitem.h
/usr/include/qt5/QtDataVisualization/qsurfacedataproxy.h
/usr/include/qt5/QtDataVisualization/qtdatavisualizationversion.h
/usr/include/qt5/QtDataVisualization/qtouch3dinputhandler.h
/usr/include/qt5/QtDataVisualization/qutils.h
/usr/include/qt5/QtDataVisualization/qvalue3daxis.h
/usr/include/qt5/QtDataVisualization/qvalue3daxisformatter.h
/usr/lib64/cmake/Qt5DataVisualization/Qt5DataVisualizationConfig.cmake
/usr/lib64/cmake/Qt5DataVisualization/Qt5DataVisualizationConfigVersion.cmake
/usr/lib64/libQt5DataVisualization.prl
/usr/lib64/libQt5DataVisualization.so
/usr/lib64/pkgconfig/Qt5DataVisualization.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri

%files examples
%defattr(-,root,root,-)
/usr/share/qt5/examples/datavisualization/audiolevels/audiolevels.cpp
/usr/share/qt5/examples/datavisualization/audiolevels/audiolevels.h
/usr/share/qt5/examples/datavisualization/audiolevels/audiolevels.pro
/usr/share/qt5/examples/datavisualization/audiolevels/audiolevelsiodevice.cpp
/usr/share/qt5/examples/datavisualization/audiolevels/audiolevelsiodevice.h
/usr/share/qt5/examples/datavisualization/audiolevels/main.cpp
/usr/share/qt5/examples/datavisualization/bars/bars.pro
/usr/share/qt5/examples/datavisualization/bars/graphmodifier.cpp
/usr/share/qt5/examples/datavisualization/bars/graphmodifier.h
/usr/share/qt5/examples/datavisualization/bars/main.cpp
/usr/share/qt5/examples/datavisualization/custominput/custominput.pro
/usr/share/qt5/examples/datavisualization/custominput/custominput.qrc
/usr/share/qt5/examples/datavisualization/custominput/custominputhandler.cpp
/usr/share/qt5/examples/datavisualization/custominput/custominputhandler.h
/usr/share/qt5/examples/datavisualization/custominput/data/data.txt
/usr/share/qt5/examples/datavisualization/custominput/main.cpp
/usr/share/qt5/examples/datavisualization/custominput/scatterdatamodifier.cpp
/usr/share/qt5/examples/datavisualization/custominput/scatterdatamodifier.h
/usr/share/qt5/examples/datavisualization/customitems/customitemgraph.cpp
/usr/share/qt5/examples/datavisualization/customitems/customitemgraph.h
/usr/share/qt5/examples/datavisualization/customitems/customitems.pro
/usr/share/qt5/examples/datavisualization/customitems/customitems.qrc
/usr/share/qt5/examples/datavisualization/customitems/layer_1.png
/usr/share/qt5/examples/datavisualization/customitems/layer_2.png
/usr/share/qt5/examples/datavisualization/customitems/layer_3.png
/usr/share/qt5/examples/datavisualization/customitems/main.cpp
/usr/share/qt5/examples/datavisualization/customitems/oilrig.obj
/usr/share/qt5/examples/datavisualization/customitems/pipe.obj
/usr/share/qt5/examples/datavisualization/customitems/refinery.obj
/usr/share/qt5/examples/datavisualization/customproxy/customproxy.pro
/usr/share/qt5/examples/datavisualization/customproxy/customproxy.qrc
/usr/share/qt5/examples/datavisualization/customproxy/data/raindata.txt
/usr/share/qt5/examples/datavisualization/customproxy/main.cpp
/usr/share/qt5/examples/datavisualization/customproxy/rainfallgraph.cpp
/usr/share/qt5/examples/datavisualization/customproxy/rainfallgraph.h
/usr/share/qt5/examples/datavisualization/customproxy/variantbardatamapping.cpp
/usr/share/qt5/examples/datavisualization/customproxy/variantbardatamapping.h
/usr/share/qt5/examples/datavisualization/customproxy/variantbardataproxy.cpp
/usr/share/qt5/examples/datavisualization/customproxy/variantbardataproxy.h
/usr/share/qt5/examples/datavisualization/customproxy/variantdataset.cpp
/usr/share/qt5/examples/datavisualization/customproxy/variantdataset.h
/usr/share/qt5/examples/datavisualization/datavisualization.pro
/usr/share/qt5/examples/datavisualization/draggableaxes/axesinputhandler.cpp
/usr/share/qt5/examples/datavisualization/draggableaxes/axesinputhandler.h
/usr/share/qt5/examples/datavisualization/draggableaxes/data.cpp
/usr/share/qt5/examples/datavisualization/draggableaxes/data.h
/usr/share/qt5/examples/datavisualization/draggableaxes/draggableaxes.pro
/usr/share/qt5/examples/datavisualization/draggableaxes/main.cpp
/usr/share/qt5/examples/datavisualization/examples.pri
/usr/share/qt5/examples/datavisualization/itemmodel/itemmodel.pro
/usr/share/qt5/examples/datavisualization/itemmodel/main.cpp
/usr/share/qt5/examples/datavisualization/qmlaxisdrag/main.cpp
/usr/share/qt5/examples/datavisualization/qmlaxisdrag/qml/qmlaxisdrag/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlaxisdrag/qml/qmlaxisdrag/cube.obj
/usr/share/qt5/examples/datavisualization/qmlaxisdrag/qml/qmlaxisdrag/cubetexture.png
/usr/share/qt5/examples/datavisualization/qmlaxisdrag/qml/qmlaxisdrag/main.qml
/usr/share/qt5/examples/datavisualization/qmlaxisdrag/qmlaxisdrag.pro
/usr/share/qt5/examples/datavisualization/qmlaxisdrag/qmlaxisdrag.qrc
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/customformatter.cpp
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/customformatter.h
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/main.cpp
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/qml/qmlaxisformatter/Data.qml
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/qml/qmlaxisformatter/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/qml/qmlaxisformatter/main.qml
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/qmlaxisformatter.pro
/usr/share/qt5/examples/datavisualization/qmlaxisformatter/qmlaxisformatter.qrc
/usr/share/qt5/examples/datavisualization/qmlbars/main.cpp
/usr/share/qt5/examples/datavisualization/qmlbars/qml/qmlbars/Axes.qml
/usr/share/qt5/examples/datavisualization/qmlbars/qml/qmlbars/Data.qml
/usr/share/qt5/examples/datavisualization/qmlbars/qml/qmlbars/main.qml
/usr/share/qt5/examples/datavisualization/qmlbars/qmlbars.pro
/usr/share/qt5/examples/datavisualization/qmlbars/qmlbars.qrc
/usr/share/qt5/examples/datavisualization/qmlcustominput/main.cpp
/usr/share/qt5/examples/datavisualization/qmlcustominput/qml/qmlcustominput/Data.qml
/usr/share/qt5/examples/datavisualization/qmlcustominput/qml/qmlcustominput/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlcustominput/qml/qmlcustominput/main.qml
/usr/share/qt5/examples/datavisualization/qmlcustominput/qmlcustominput.pro
/usr/share/qt5/examples/datavisualization/qmlcustominput/qmlcustominput.qrc
/usr/share/qt5/examples/datavisualization/qmllegend/main.cpp
/usr/share/qt5/examples/datavisualization/qmllegend/qml/qmllegend/Data.qml
/usr/share/qt5/examples/datavisualization/qmllegend/qml/qmllegend/LegendItem.qml
/usr/share/qt5/examples/datavisualization/qmllegend/qml/qmllegend/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmllegend/qml/qmllegend/main.qml
/usr/share/qt5/examples/datavisualization/qmllegend/qmllegend.pro
/usr/share/qt5/examples/datavisualization/qmllegend/qmllegend.qrc
/usr/share/qt5/examples/datavisualization/qmlmultigraph/main.cpp
/usr/share/qt5/examples/datavisualization/qmlmultigraph/qml/qmlmultigraph/Data.qml
/usr/share/qt5/examples/datavisualization/qmlmultigraph/qml/qmlmultigraph/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlmultigraph/qml/qmlmultigraph/main.qml
/usr/share/qt5/examples/datavisualization/qmlmultigraph/qmlmultigraph.pro
/usr/share/qt5/examples/datavisualization/qmlmultigraph/qmlmultigraph.qrc
/usr/share/qt5/examples/datavisualization/qmloscilloscope/datasource.cpp
/usr/share/qt5/examples/datavisualization/qmloscilloscope/datasource.h
/usr/share/qt5/examples/datavisualization/qmloscilloscope/main.cpp
/usr/share/qt5/examples/datavisualization/qmloscilloscope/qml/qmloscilloscope/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmloscilloscope/qml/qmloscilloscope/main.qml
/usr/share/qt5/examples/datavisualization/qmloscilloscope/qmloscilloscope.pro
/usr/share/qt5/examples/datavisualization/qmloscilloscope/qmloscilloscope.qrc
/usr/share/qt5/examples/datavisualization/qmlscatter/main.cpp
/usr/share/qt5/examples/datavisualization/qmlscatter/qml/qmlscatter/Data.qml
/usr/share/qt5/examples/datavisualization/qmlscatter/qml/qmlscatter/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlscatter/qml/qmlscatter/main.qml
/usr/share/qt5/examples/datavisualization/qmlscatter/qmlscatter.pro
/usr/share/qt5/examples/datavisualization/qmlscatter/qmlscatter.qrc
/usr/share/qt5/examples/datavisualization/qmlspectrogram/main.cpp
/usr/share/qt5/examples/datavisualization/qmlspectrogram/qml/qmlspectrogram/Data.qml
/usr/share/qt5/examples/datavisualization/qmlspectrogram/qml/qmlspectrogram/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlspectrogram/qml/qmlspectrogram/main.qml
/usr/share/qt5/examples/datavisualization/qmlspectrogram/qmlspectrogram.pro
/usr/share/qt5/examples/datavisualization/qmlspectrogram/qmlspectrogram.qrc
/usr/share/qt5/examples/datavisualization/qmlsurface/heightmap.png
/usr/share/qt5/examples/datavisualization/qmlsurface/main.cpp
/usr/share/qt5/examples/datavisualization/qmlsurface/qml/qmlsurface/Data.qml
/usr/share/qt5/examples/datavisualization/qmlsurface/qml/qmlsurface/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlsurface/qml/qmlsurface/main.qml
/usr/share/qt5/examples/datavisualization/qmlsurface/qmlsurface.pro
/usr/share/qt5/examples/datavisualization/qmlsurface/qmlsurface.qrc
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/layer_1.png
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/layer_2.png
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/layer_3.png
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/main.cpp
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/qml/qmlsurfacelayers/NewButton.qml
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/qml/qmlsurfacelayers/main.qml
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/qmlsurfacelayers.pro
/usr/share/qt5/examples/datavisualization/qmlsurfacelayers/qmlsurfacelayers.qrc
/usr/share/qt5/examples/datavisualization/rotations/main.cpp
/usr/share/qt5/examples/datavisualization/rotations/mesh/largesphere.obj
/usr/share/qt5/examples/datavisualization/rotations/mesh/narrowarrow.obj
/usr/share/qt5/examples/datavisualization/rotations/rotations.pro
/usr/share/qt5/examples/datavisualization/rotations/rotations.qrc
/usr/share/qt5/examples/datavisualization/rotations/scatterdatamodifier.cpp
/usr/share/qt5/examples/datavisualization/rotations/scatterdatamodifier.h
/usr/share/qt5/examples/datavisualization/scatter/main.cpp
/usr/share/qt5/examples/datavisualization/scatter/scatter.pro
/usr/share/qt5/examples/datavisualization/scatter/scatterdatamodifier.cpp
/usr/share/qt5/examples/datavisualization/scatter/scatterdatamodifier.h
/usr/share/qt5/examples/datavisualization/surface/main.cpp
/usr/share/qt5/examples/datavisualization/surface/mountain.png
/usr/share/qt5/examples/datavisualization/surface/surface.pro
/usr/share/qt5/examples/datavisualization/surface/surface.qrc
/usr/share/qt5/examples/datavisualization/surface/surfacegraph.cpp
/usr/share/qt5/examples/datavisualization/surface/surfacegraph.h
/usr/share/qt5/examples/datavisualization/texturesurface/custominputhandler.cpp
/usr/share/qt5/examples/datavisualization/texturesurface/custominputhandler.h
/usr/share/qt5/examples/datavisualization/texturesurface/highlightseries.cpp
/usr/share/qt5/examples/datavisualization/texturesurface/highlightseries.h
/usr/share/qt5/examples/datavisualization/texturesurface/main.cpp
/usr/share/qt5/examples/datavisualization/texturesurface/maptexture.jpg
/usr/share/qt5/examples/datavisualization/texturesurface/surfacegraph.cpp
/usr/share/qt5/examples/datavisualization/texturesurface/surfacegraph.h
/usr/share/qt5/examples/datavisualization/texturesurface/texturedsurface.qrc
/usr/share/qt5/examples/datavisualization/texturesurface/texturesurface.pro
/usr/share/qt5/examples/datavisualization/texturesurface/topographicseries.cpp
/usr/share/qt5/examples/datavisualization/texturesurface/topographicseries.h
/usr/share/qt5/examples/datavisualization/texturesurface/topography.png
/usr/share/qt5/examples/datavisualization/volumetric/layer_ground.png
/usr/share/qt5/examples/datavisualization/volumetric/layer_magma.png
/usr/share/qt5/examples/datavisualization/volumetric/layer_water.png
/usr/share/qt5/examples/datavisualization/volumetric/main.cpp
/usr/share/qt5/examples/datavisualization/volumetric/volumetric.cpp
/usr/share/qt5/examples/datavisualization/volumetric/volumetric.h
/usr/share/qt5/examples/datavisualization/volumetric/volumetric.pro
/usr/share/qt5/examples/datavisualization/volumetric/volumetric.qrc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5DataVisualization.so.5
/usr/lib64/libQt5DataVisualization.so.5.15
/usr/lib64/libQt5DataVisualization.so.5.15.2
/usr/lib64/qt5/qml/QtDataVisualization/designer/Bars3DSpecifics.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/Scatter3DSpecifics.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/Surface3DSpecifics.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/default/Bars3D.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/default/Scatter3D.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/default/Surface3D.qml
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/bars3d-icon.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/bars3d-icon16.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/scatter3d-icon.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/scatter3d-icon16.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/surface3d-icon.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/images/surface3d-icon16.png
/usr/lib64/qt5/qml/QtDataVisualization/designer/qtdatavisualization.metainfo
/usr/lib64/qt5/qml/QtDataVisualization/libdatavisualizationqml2.so
/usr/lib64/qt5/qml/QtDataVisualization/plugins.qmltypes
/usr/lib64/qt5/qml/QtDataVisualization/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtdatavis3d/8624bcdae55baeef00cd11d5dfcfa60f68710a02
